# ---- Site Basics ----
title: "Wanjin Blog"
name: "Wanjin Choi"
description: "Notes on coding, RPA, and more"
locale: "ko-KR"
timezone: "Asia/Seoul"

url: "https://wanjinchoi.github.io"
baseurl: ""   # 사용자 사이트는 빈 값

# 깃허브 저장소(표기/기능에 도움)
repository: "wanjinchoi/wanjinchoi.github.io"

# ---- Theme ----
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"   # "air", "aqua", "contrast", "dark", "dirt", "mint", "neon", "plum", "sunrise"

# ---- Plugins (GitHub Pages 허용 범위) ----
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate


google_analytics: G-XXXXXXX
# ---- Build / Output ----
paginate: 7
paginate_path: "/page:num/"
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
future: false

# ---- UI Options ----
logo: "/assets/img/wanjin.jpg"   # 없으면 주석 처리
search: true                     # 상단 검색
breadcrumbs: true
breadcrumbs_home_label: "Home"
show_date: true

# ---- Defaults (포스트 기본값) ----
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      toc: true
      toc_sticky: true
      toc_label: "목차"

# ---- Author (사이드바 프로필) ----
author:
  name: "Wanjin Choi"
  avatar: "/assets/img/wanjin.jpg"  # 이미지 없으면 주석
  bio: "RPA/Automation, AWS, IoT/Modbus 실험 기록."
  location: "Seoul, KR"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/wanjinchoi"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:you@example.com"

# ---- Nav (상단 메뉴 파일을 쓰도록) ----
#  _data/navigation.yml 사용
# header_pages 대신 navigation.yml을 권장

# ---- Collections (필요하면 추가) ----
# collections:
#   projects:
#     output: true
#     permalink: /projects/:path/

# ---- Feeds / SEO ----
atom_feed:
  hide: false